version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=your-super-secret-jwt-key-change-me-in-production
      - PORT=8080
      - DB_PATH=./storage/chart-organizer.db
      - DATASET_STORAGE_PATH=./storage/datasets
    volumes:
      - ./storage:/root/storage
      - chart-organizer-storage:/root/storage
    networks:
      - chart-organizer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - chart-organizer-network

networks:
  chart-organizer-network:
    driver: bridge

volumes:
  chart-organizer-storage: